# Generated by Django 3.1.7 on 2021-03-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254)),
                ('option1', models.CharField(max_length=254)),
                ('option2', models.CharField(max_length=254)),
                ('option3', models.CharField(max_length=254)),
                ('option4', models.CharField(max_length=254)),
                ('correct_answer', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=256)),
                ('Duration', models.CharField(max_length=2)),
                ('Exam_title', models.CharField(max_length=120)),
                ('Question_file', models.FileField(upload_to='written_question')),
                ('Publish_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
