# Generated by Django 3.1.7 on 2021-03-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
        ('App_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenExamAnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submit_time', models.TimeField(auto_created=True)),
                ('Answer_paper', models.FileField(upload_to='answer_paper')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerer', to='App_login.studentinfo')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_type', to='App_test.written')),
            ],
        ),
    ]
